---
abstract: 'Perl module X'
author:
  - 'Your Name <you@example.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: X
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Tiny: '0'
  Import::Into: '0'
  URI: '0'
  perl: '5.008001'
  strict: '0'
  utf8::all: '0'
  warnings: '0'
resources:
  repository: https://github.com/yourusername/p5-X.git
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
